// USANDO O LET EM LOOP

//  INSTRUÇÃO FOR

for (let i = 0; i < 10; i++) {
    console.log(i)
}

console.log('i = ', i)

// FOR CRIA UM LOOP COM 3 EXPRESSÕES OPICIONAIS

// 1 - E EXECUTADA (UMA VEZ) ANTES DA EXECUÇÃO DO BLOCO DE CODIGO
// 2 - DEFINE A CONDIÇÃO PARA EXECUÇÃO DO BLOCO DE CODIGO
// 3 - E EXECUTADA (TODA VEZ) APOS O BLOCO DE CODIGO TER SIDO EXECUTADO

/*
FOR (EXPRESSÃO 1, EXPRESSÃO 2, EXPRESSÃO 3) {
    BLOCODE COFIGO A SER EXECUTADO
}
*/


//Não é possivel acessar o let fora do loop